<?php
$form = $this->form;
$meetup = $this->meetup;

$title = $form->get('title');
$title->setAttribute('class', 'form-control');
$title->setAttribute('placeholder', 'Post title');

$text = $form->get('description');
$text->setAttribute('class', 'form-control');
$text->setAttribute('placeholder', 'Post content');

$submit = $form->get('submit');
$submit->setValue($this->submitLabel);
$submit->setAttribute('class', 'btn btn-primary');

$form->prepare();

echo $this->form()->openTag($form);
?>

    <fieldset>
        <div class="form-group">
            <?= $this->formLabel($title) ?>
            <?= $this->formElement($title) ?>
            <?= $this->formElementErrors()->render($title, ['class' => 'help-block']) ?>
        </div>

        <div class="form-group">
            <?= $this->formLabel($text) ?>
            <?= $this->formElement($text) ?>
            <?= $this->formElementErrors()->render($text, ['class' => 'help-block']) ?>
        </div>
    </fieldset>

<?php
echo $this->formSubmit($submit);
echo $this->form()->closeTag();